name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies and run tests
        working-directory: ./front
        run: npm install && npm test -- --watch=false --code-coverage --browsers=ChromeHeadlessCI

      - name: Copy frontend coverage report
        run: mkdir -p ./back/target/sonar/coverage && cp ./front/coverage/bobapp/lcov.info ./back/target/sonar/coverage/lcov.info
          
      - name: Build and verify backend with Maven
        working-directory: ./back
        run: mvn verify

      - name: Verify lcov.info exists
        run: |
          if [ ! -f ./back/target/sonar/coverage/lcov.info ]; then
            echo "lcov.info not found!"
            exit 1
          else
            echo "lcov.info found."
          fi

      - name: SonarQube Scan
        working-directory: ./back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=fmmaesor_mod10 -Dsonar.organization=fmmaesor -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.javascript.lcov.reportPaths=./back/target/sonar/coverage/lcov.info -Dsonar.qualitygate.wait=true
